movie_title = []
movie_overview = []
movie_source = []
movie_date = []
movie_title2 = []
movie_overview2 = []
movie_source2 = []
movie_date2 = []
movie_title3 = []
movie_overview3 = []
movie_source3 = []
movie_date3 = []

alm = ["spiderman", "Goal", "joker", "Transformer", "avatar", "hacker",
       "Gemini", "Aladdin", "Cars", "Avengers", "venom", "gladiator", "Godzilla", "Inception", "crawl", "ant-man", "star-wars", "deadpool"]
alm2 = ["Gemini", "Aladdin", "Cars", "Avengers", "venom", "gladiator"]
alm3 = ["Godzilla", "Inception", "crawl", "ant-man", "star-wars", "deadpool"]
